import type { INodeProperties } from 'n8n-workflow';
import { mergeJsonBody } from '../../../shared/mergeJsonBody';
import { idProperty } from '../../shared/descriptions';

const resource = 'paylink';
const show = { resource: [resource] };

/**
 * Paylinks — https://developers.payrexx.com/reference/create-a-paylink
 *
 * Careful with the paths: a paylink lives under `/Invoice/`, while what Payrexx
 * calls an invoice lives under `/Bill/`. That is the API's own naming, kept here
 * so the requests match the documentation.
 */
export const paylinkDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a paylink',
				routing: {
					request: { method: 'POST', url: '/Invoice/' },
					send: { preSend: [mergeJsonBody('additionalFields', 'Additional Fields')] },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a paylink',
				routing: { request: { method: 'GET', url: '=/Invoice/{{$parameter.paylinkId}}/' } },
			},
			{
				name: 'Remove',
				value: 'remove',
				action: 'Remove a paylink',
				routing: { request: { method: 'DELETE', url: '=/Invoice/{{$parameter.paylinkId}}/' } },
			},
		],
		default: 'create',
	},

	idProperty('Paylink ID', 'paylinkId', resource, ['get', 'remove'], 'The ID of the paylink'),

	// ─── Create ────────────────────────────────────────────────────────────────
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		required: true,
		description: 'Page title shown on the payment page',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'title' } },
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		required: true,
		description: 'Description shown on the payment page',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'description' } },
	},
	{
		displayName: 'Purpose',
		name: 'purpose',
		type: 'string',
		default: '',
		required: true,
		description: 'What the payer is paying for',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'purpose' } },
	},
	{
		displayName: 'Reference ID',
		name: 'referenceId',
		type: 'string',
		default: '',
		required: true,
		description: 'Your own reference for this payment',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'referenceId' } },
	},
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		default: 0,
		required: true,
		description: 'Amount in cents',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'amount' } },
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		default: 'CHF',
		required: true,
		description: 'Currency in ISO-4217 format, three capital letters',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'currency' } },
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { ...show, operation: ['create'] } },
		options: [
			{
				displayName: 'Button Text',
				name: 'buttonText',
				type: 'string',
				default: '',
				description: 'Custom label for the pay button',
				routing: { send: { type: 'body', property: 'buttonText' } },
			},
			{
				displayName: 'Expiration Date',
				name: 'expirationDate',
				type: 'string',
				default: '',
				placeholder: '2026-12-31',
				description: 'Date the link stops working',
				routing: { send: { type: 'body', property: 'expirationDate' } },
			},
			{
				displayName: 'Failed Redirect URL',
				name: 'failedRedirectUrl',
				type: 'string',
				default: '',
				description: 'Where the payer lands after a failed payment',
				routing: { send: { type: 'body', property: 'failedRedirectUrl' } },
			},
			{
				displayName: 'Hide Contact Fields',
				name: 'hideFields',
				type: 'boolean',
				default: false,
				description: 'Whether to hide the whole contact field section on the page',
				routing: { send: { type: 'body', property: 'hideFields' } },
			},
			{
				displayName: 'Internal Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Name of the payment page, shown to administrators only',
				routing: { send: { type: 'body', property: 'name' } },
			},
			{
				displayName: 'Payment Means',
				name: 'pm',
				type: 'string',
				typeOptions: { multipleValues: true, multipleValueButtonText: 'Add Payment Mean' },
				default: [],
				description: 'Payment mean names to offer',
				routing: { send: { type: 'body', property: 'pm' } },
			},
			{
				displayName: 'Pre-Authorization',
				name: 'preAuthorization',
				type: 'boolean',
				default: false,
				description: 'Whether to charge the payment manually later, as an authorization',
				routing: { send: { type: 'body', property: 'preAuthorization' } },
			},
			{
				displayName: 'PSP',
				name: 'psp',
				type: 'string',
				typeOptions: { multipleValues: true, multipleValueButtonText: 'Add PSP' },
				default: [],
				description: 'IDs of the payment service providers to offer',
				routing: { send: { type: 'body', property: 'psp' } },
			},
			{
				displayName: 'Reservation',
				name: 'reservation',
				type: 'boolean',
				default: false,
				description: 'Whether to charge the payment manually later, as a reservation',
				routing: { send: { type: 'body', property: 'reservation' } },
			},
			{
				displayName: 'SKU',
				name: 'sku',
				type: 'string',
				default: '',
				description: 'Product stock keeping unit',
				routing: { send: { type: 'body', property: 'sku' } },
			},
			{
				displayName: 'Subscription Cancellation Interval',
				name: 'subscriptionCancellationInterval',
				type: 'string',
				default: '',
				placeholder: 'P1M',
				description: 'Notice period, as a PHP date interval',
				routing: { send: { type: 'body', property: 'subscriptionCancellationInterval' } },
			},
			{
				displayName: 'Subscription Interval',
				name: 'subscriptionInterval',
				type: 'string',
				default: '',
				placeholder: 'P1M',
				description: 'Payment interval, as a PHP date interval',
				routing: { send: { type: 'body', property: 'subscriptionInterval' } },
			},
			{
				displayName: 'Subscription Period',
				name: 'subscriptionPeriod',
				type: 'string',
				default: '',
				placeholder: 'P1Y',
				description: 'Duration of the subscription, as a PHP date interval',
				routing: { send: { type: 'body', property: 'subscriptionPeriod' } },
			},
			{
				displayName: 'Subscription State',
				name: 'subscriptionState',
				type: 'boolean',
				default: false,
				description: 'Whether the payment sets up a subscription',
				routing: { send: { type: 'body', property: 'subscriptionState' } },
			},
			{
				displayName: 'Success Redirect URL',
				name: 'successRedirectUrl',
				type: 'string',
				default: '',
				description: 'Where the payer lands after a successful payment',
				routing: { send: { type: 'body', property: 'successRedirectUrl' } },
			},
			{
				displayName: 'VAT Rate',
				name: 'vatRate',
				type: 'number',
				default: 0,
				description: 'VAT rate in percent',
				routing: { send: { type: 'body', property: 'vatRate' } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'json',
		default: '{}',
		description:
			'Extra keys merged into the request body, for the parts of the paylink payload this node does not model — the contact "fields" list, attachments, concardisOrderId',
		displayOptions: { show: { ...show, operation: ['create'] } },
	},
];
