import type {
	IAuthenticateGeneric,
	ICredentialTestRequest,
	ICredentialType,
	Icon,
	INodeProperties,
} from 'n8n-workflow';

/**
 * Webling — the association management system Swiss clubs and NGOs run their
 * membership, accounting and correspondence on.
 *
 * Each account is its own subdomain, so the base URL is per customer. The key is
 * generated by an administrator under Administration → API and carries that
 * administrator's permissions: a key scoped to one member group sees nothing
 * outside it, which is why an empty result can mean the key is scoped too
 * narrowly rather than that nothing matched.
 *
 * The key may travel as an `apikey` query parameter or an `apikey` header; the
 * header is used here so it stays out of logs and proxy access records.
 *
 * https://demo.webling.ch/api/1
 */
export class WeblingApi implements ICredentialType {
	name = 'weblingApi';

	displayName = 'Webling API';

	documentationUrl = 'https://demo.webling.ch/api/1';

	icon: Icon = {
		light: 'file:../icons/webling.svg',
		dark: 'file:../icons/webling.dark.svg',
	};

	properties: INodeProperties[] = [
		{
			displayName: 'Base URL',
			name: 'baseUrl',
			type: 'string',
			default: '',
			required: true,
			placeholder: 'https://yourclub.webling.ch',
			description:
				'Root URL of the Webling account, without a trailing slash and without /api. Self-hosted installations may use their own domain.',
		},
		{
			displayName: 'API Key',
			name: 'apiKey',
			type: 'string',
			typeOptions: { password: true },
			default: '',
			required: true,
			description: 'Generated in the web app under Administration → API',
		},
	];

	authenticate: IAuthenticateGeneric = {
		type: 'generic',
		properties: {
			headers: {
				apikey: '={{$credentials.apiKey}}',
			},
		},
	};

	/** Webling documents /currentuser as the way to check a key is still valid. */
	test: ICredentialTestRequest = {
		request: {
			baseURL: '={{$credentials.baseUrl}}',
			url: '/api/1/currentuser',
			method: 'GET',
		},
	};
}
