import type { INodeProperties } from 'n8n-workflow';
import { customParametersProperty, uuidProperty } from '../../shared/descriptions';

const resource = 'payment';
const show = { resource: [resource] };

/**
 * https://docs.raisenow.com/api — Payments.
 *
 * `init` is the entry point of every payment flow: it creates the payment and
 * returns either a final state or the redirect/action the donor has to complete.
 */
export const paymentDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show },
		options: [
			{
				name: 'Cancel',
				value: 'cancel',
				action: 'Cancel a payment',
				routing: {
					request: { method: 'POST', url: '=/payments/{{$parameter.paymentUuid}}/cancel' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a payment',
				routing: {
					request: { method: 'GET', url: '=/payments/{{$parameter.paymentUuid}}' },
				},
			},
			{
				name: 'Initialize',
				value: 'init',
				action: 'Initialize a payment',
				routing: {
					request: { method: 'POST', url: '/payments' },
				},
			},
			{
				name: 'Refund',
				value: 'refund',
				action: 'Refund a payment',
				routing: {
					request: { method: 'POST', url: '=/payments/{{$parameter.paymentUuid}}/refunds' },
				},
			},
		],
		default: 'init',
	},

	uuidProperty(
		'Payment UUID',
		'paymentUuid',
		resource,
		['get', 'cancel', 'refund'],
		'The identifier of the payment',
	),

	// ─── Initialize ────────────────────────────────────────────────────────────
	{
		displayName: 'Account UUID',
		name: 'accountUuid',
		type: 'string',
		default: '',
		required: true,
		description: "UUID of the merchant's account",
		displayOptions: { show: { ...show, operation: ['init'] } },
		routing: { send: { type: 'body', property: 'account_uuid' } },
	},
	{
		displayName: 'Payment Method',
		name: 'paymentMethod',
		type: 'string',
		default: 'card',
		placeholder: 'card',
		description:
			'Payment method to use, e.g. card or twint. Uses the default profile for the method unless a profile is set. Either this or Profile is required.',
		displayOptions: { show: { ...show, operation: ['init'] } },
		routing: { send: { type: 'body', property: 'payment_method' } },
	},
	{
		displayName: 'Amount',
		name: 'amountValue',
		type: 'string',
		default: '',
		required: true,
		placeholder: '1000',
		description: 'Amount in the minor units of the currency, so 1000 means 10.00',
		displayOptions: { show: { ...show, operation: ['init'] } },
		routing: { send: { type: 'body', property: 'amount.value' } },
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		default: 'CHF',
		required: true,
		description: 'Currency in ISO-4217 format, three capital letters',
		displayOptions: { show: { ...show, operation: ['init'] } },
		routing: { send: { type: 'body', property: 'amount.currency' } },
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { ...show, operation: ['init'] } },
		options: [
			{
				displayName: 'Create Payment Source',
				name: 'create_payment_source',
				type: 'boolean',
				default: false,
				description:
					'Whether to save the payment instrument so it can be charged again later, e.g. for a subscription',
				routing: { send: { type: 'body', property: 'create_payment_source' } },
			},
			{
				displayName: 'Create Supporter',
				name: 'create_supporter',
				type: 'boolean',
				default: false,
				description: 'Whether to create a Supporter Store entry from the supporter fields',
				routing: { send: { type: 'body', property: 'create_supporter' } },
			},
			customParametersProperty(),
			{
				displayName: 'Locale',
				name: 'locale',
				type: 'string',
				default: '',
				placeholder: 'de_CH',
				description: 'Locale to use when interacting with the donor',
				routing: { send: { type: 'body', property: 'locale' } },
			},
			{
				displayName: 'Profile',
				name: 'profile',
				type: 'string',
				default: '',
				placeholder: 'cards_in_switzerland',
				description: 'Payment method profile to use, instead of the default for the method',
				routing: { send: { type: 'body', property: 'profile' } },
			},
			{
				displayName: 'Return URL',
				name: 'return_url',
				type: 'string',
				default: '',
				placeholder: 'https://www.my-charity.org/thank-you',
				description: 'Where the donor is redirected once the payment flow is finished',
				routing: { send: { type: 'body', property: 'return_url' } },
			},
		],
	},
	{
		displayName: 'Supporter',
		name: 'supporter',
		type: 'collection',
		placeholder: 'Add Supporter Field',
		default: {},
		description: 'Donor details sent with the payment',
		displayOptions: { show: { ...show, operation: ['init'] } },
		options: [
			{
				displayName: 'Address Addendum',
				name: 'address_addendum',
				type: 'string',
				default: '',
				description: 'Second line of the address',
				routing: { send: { type: 'body', property: 'supporter.address_addendum' } },
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'supporter.city' } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				placeholder: 'CH',
				description: 'Country in ISO-3166 alpha-2, two uppercase letters',
				routing: { send: { type: 'body', property: 'supporter.country' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				routing: { send: { type: 'body', property: 'supporter.email' } },
			},
			{
				displayName: 'Email Permission',
				name: 'email_permission',
				type: 'boolean',
				default: false,
				description: 'Whether the merchant may send emails to this supporter',
				routing: { send: { type: 'body', property: 'supporter.email_permission' } },
			},
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'supporter.first_name' } },
			},
			{
				displayName: 'House Number',
				name: 'house_number',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'supporter.house_number' } },
			},
			{
				displayName: 'Last Name',
				name: 'last_name',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'supporter.last_name' } },
			},
			{
				displayName: 'Postal Code',
				name: 'postal_code',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'supporter.postal_code' } },
			},
			{
				displayName: 'Salutation',
				name: 'salutation',
				type: 'string',
				default: '',
				placeholder: 'ms',
				routing: { send: { type: 'body', property: 'supporter.salutation' } },
			},
			{
				displayName: 'Street',
				name: 'street',
				type: 'string',
				default: '',
				description: 'First line of the address',
				routing: { send: { type: 'body', property: 'supporter.street' } },
			},
			{
				displayName: 'Supporter Custom Parameters',
				name: 'supporterCustomParameters',
				type: 'json',
				default: '{}',
				description: 'Free key-value pairs on the supporter. Values must be strings.',
				routing: {
					send: {
						type: 'body',
						property: 'supporter.custom_parameters',
						value: '={{ JSON.parse($value || "{}") }}',
					},
				},
			},
			{
				displayName: 'Supporter UUID',
				name: 'uuid',
				type: 'string',
				default: '',
				description: 'UUID of the supporter, if it already exists in Supporter Store',
				routing: { send: { type: 'body', property: 'supporter.uuid' } },
			},
		],
	},
	{
		displayName: 'Payment Information',
		name: 'paymentInformation',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		description:
			'Only for payment methods where the instrument is passed directly, such as raw card data. Leave empty for redirect-based methods.',
		displayOptions: { show: { ...show, operation: ['init'] } },
		options: [
			{
				displayName: 'Brand',
				name: 'brand',
				type: 'string',
				default: '',
				placeholder: 'visa',
				routing: { send: { type: 'body', property: 'payment_information.brand' } },
			},
			{
				displayName: 'Cardholder',
				name: 'cardholder',
				type: 'string',
				default: '',
				description: 'Cardholder name as written on the card',
				routing: { send: { type: 'body', property: 'payment_information.cardholder' } },
			},
			{
				displayName: 'CVV',
				name: 'cvv',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				routing: { send: { type: 'body', property: 'payment_information.cvv' } },
			},
			{
				displayName: 'Expiry Month',
				name: 'expiry_month',
				type: 'number',
				default: 1,
				routing: { send: { type: 'body', property: 'payment_information.expiry_month' } },
			},
			{
				displayName: 'Expiry Year',
				name: 'expiry_year',
				type: 'number',
				default: 2030,
				description: 'Four-digit expiry year',
				routing: { send: { type: 'body', property: 'payment_information.expiry_year' } },
			},
			{
				displayName: 'Number',
				name: 'number',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'Card number, without spaces',
				routing: { send: { type: 'body', property: 'payment_information.number' } },
			},
		],
	},
	{
		displayName: 'Subscription',
		name: 'subscription',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		description: 'Turns the payment into a recurring one',
		displayOptions: { show: { ...show, operation: ['init'] } },
		options: [
			{
				displayName: 'Plan UUID',
				name: 'plan_uuid',
				type: 'string',
				default: '',
				description: 'UUID of the subscription plan to use',
				routing: { send: { type: 'body', property: 'subscription.plan_uuid' } },
			},
			{
				displayName: 'Planned Effective From',
				name: 'planned_effective_from',
				type: 'string',
				default: '',
				placeholder: '2024-05-12',
				description: 'Date after which the subscription can be charged, as YYYY-MM-DD',
				routing: { send: { type: 'body', property: 'subscription.planned_effective_from' } },
			},
			{
				displayName: 'Planned End',
				name: 'planned_end',
				type: 'string',
				default: '',
				placeholder: '2025-04-30',
				description: 'Date until which the subscription can be charged, as YYYY-MM-DD',
				routing: { send: { type: 'body', property: 'subscription.planned_end' } },
			},
			{
				displayName: 'Recurring Interval',
				name: 'recurring_interval',
				type: 'string',
				default: '1 * *',
				description:
					'Charge interval in day-of-month, month, weekday form, so "1 * *" charges on the first of every month',
				routing: { send: { type: 'body', property: 'subscription.recurring_interval' } },
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'Europe/Zurich',
				description: 'Timezone used to decide when a day starts',
				routing: { send: { type: 'body', property: 'subscription.timezone' } },
			},
		],
	},
	{
		displayName: 'HMAC',
		name: 'hmac',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		description: 'Required only if the account is configured to verify signed payment requests',
		displayOptions: { show: { ...show, operation: ['init'] } },
		options: [
			{
				displayName: 'Timestamp',
				name: 'timestamp',
				type: 'number',
				default: 0,
				description: 'Unix timestamp of when the HMAC was generated',
				routing: { send: { type: 'body', property: 'hmac.timestamp' } },
			},
			{
				displayName: 'Value',
				name: 'value',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'The HMAC value',
				routing: { send: { type: 'body', property: 'hmac.value' } },
			},
		],
	},

	// ─── Cancel ────────────────────────────────────────────────────────────────
	{
		displayName: 'Reason',
		name: 'reason',
		type: 'string',
		default: '',
		description: 'Free text describing why the payment was cancelled',
		displayOptions: { show: { ...show, operation: ['cancel'] } },
		routing: { send: { type: 'body', property: 'reason' } },
	},

	// ─── Refund ────────────────────────────────────────────────────────────────
	{
		displayName: 'Refund Full Amount',
		name: 'refundFullAmount',
		type: 'boolean',
		default: true,
		description:
			'Whether to refund the whole residual amount, meaning the original amount minus previous refunds',
		displayOptions: { show: { ...show, operation: ['refund'] } },
	},
	{
		displayName: 'Amount',
		name: 'refundAmountValue',
		type: 'string',
		default: '',
		required: true,
		placeholder: '1000',
		description: 'Amount in the minor units of the currency, so 1000 means 10.00',
		displayOptions: { show: { ...show, operation: ['refund'], refundFullAmount: [false] } },
		routing: { send: { type: 'body', property: 'amount.value' } },
	},
	{
		displayName: 'Currency',
		name: 'refundCurrency',
		type: 'string',
		default: 'CHF',
		required: true,
		description: 'Currency in ISO-4217 format, three capital letters',
		displayOptions: { show: { ...show, operation: ['refund'], refundFullAmount: [false] } },
		routing: { send: { type: 'body', property: 'amount.currency' } },
	},
];
